---
language: node_js
node_js:
  - node
  - lts/*
cache:
  yarn: true
before_script:
  - npm install -g npm@latest
script:
  - yarn
  - npx jest --ci
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - yarn
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive
